- name: copy mongodb repo
  ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/momgodb.repo

- name: install mongodb client
  ansible.builtin.package:
      name: mongodb-org-shell
      state: present
- name: get the product count
  ansible.builtin.command:  mongo --host mongodb.devopstraining.space --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count
  when: component == "catalogue"

- name: get the entries count
  ansible.builtin.command:  mongo --host mongodb.devopstraining.space --quiet --eval 'db = db.getSiblingDB("users"); db.products.count()'
  register: entries_count
  when: component == "user"

# - name: print the count
#   ansible.builtin.debug:
#     msg: "product count : {{product_count}}"

- name: "load {{component}} data"
  ansible.builtin.command: mongo --host mongodb.devopstraining.space < /app/schema/"{{component}}".js
  when: product_count.stdout == "0"

- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes